namespace: community
name: aws
version: 5.5.0
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
description: null
license_file: COPYING
tags: [community, aws, cloud, amazon]
dependencies:
  amazon.aws: '>=5.0.0'
repository: https://github.com/ansible-collections/community.aws
documentation: https://ansible-collections.github.io/community.aws/branch/stable-5/collections/community/aws/index.html
homepage: https://github.com/ansible-collections/community.aws
issues: https://github.com/ansible-collections/community.aws/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
build_ignore:
  - '*cloud-config-aws.ini'
  - '*cloud-config-aws.yml'
  - 'changelogs/.plugin-cache.yaml'
