namespace: community
name: aws
version: 6.0.0-dev0
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
description: null
license_file: COPYING
tags: [community, aws, cloud, amazon]
dependencies:
  amazon.aws: '>=6.0.0-dev0'
repository: https://github.com/ansible-collections/community.aws
documentation: https://ansible-collections.github.io/community.aws/branch/main/collections/community/aws/index.html
homepage: https://github.com/ansible-collections/community.aws
issues: https://github.com/ansible-collections/community.aws/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
build_ignore:
  - '*cloud-config-aws.ini'
  - '*cloud-config-aws.yml'
  - 'changelogs/.plugin-cache.yaml'
