DESCRIBE_CLUSTER = "describe_cluster"
AWS_HSM = "aws_hsm"
CREATE_CLUSTER = "create_cluster"
CREATE_HSM = "create_hsm"
STATES = [
    "CREATE_IN_PROGRESS",
    "UNINITIALIZED",
    "INITIALIZE_IN_PROGRESS",
    "INITIALIZED",
    "ACTIVE",
    "UPDATE_IN_PROGRESS",
    "DELETE_IN_PROGRESS",
    "DELETED",
    "DEGRADED",
]
AVAILABILITY_ZONES = [
    "us-east-1a",
    "us-east-1b",
    "us-east-1c",
    "us-east-1d",
    "us-east-1e",
    "us-east-1f",
    "us-west-2a",
    "us-west-2b",
    "us-west-2c",
    "us-west-1a",
    "us-west-1b",
    "eu-west-1a",
    "eu-west-1b",
    "eu-west-1c",
    "eu-central-1a",
    "eu-central-1b",
    "ap-southeast-1a",
    "ap-southeast-1b",
    "ap-southeast-2a",
    "ap-southeast-2b",
    "ap-southeast-2c",
    "ap-northeast-1a",
    "ap-northeast-1c",
    "sa-east-1a",
    "sa-east-1b",
    "sa-east-1c",
    "ap-south-1a",
    "ap-south-1b",
]
