#!/usr/bin/env python3

from pathlib import Path

target_dir = Path('.')

ignore_dir = target_dir / "tests" / "sanity"
plugin_dir = target_dir / "plugins"
ignore_dir.mkdir(parents=True, exist_ok=True)

for version in ["2.9", "2.10", "2.11", "2.12"]:
    ignore_file = ignore_dir / f"ignore-{version}.txt"
    ignore_content = ignore_file.read_text().split("\n")
    ignore_content.append(f"tests/sanity/refresh_ignore_files shebang!skip")
    skip_list = [
        "compile-2.6!skip",  # Py3.8+
        "compile-2.7!skip",  # Py3.8+
        "compile-3.5!skip",  # Py3.8+
        "compile-3.6!skip",  # Py3.8+
        "compile-3.7!skip",  # Py3.8+
        "import-2.6!skip",  # Py3.8+
        "import-2.7!skip",  # Py3.8+
        "import-3.5!skip",  # Py3.8+
        "import-3.6!skip",  # Py3.8+
        "import-3.7!skip",  # Py3.8+
        "future-import-boilerplate!skip",  # Py2 only
        "metaclass-boilerplate!skip",  # Py2 only
    ]

    for sub_dir in plugin_dir.iterdir():
        for f in sub_dir.glob("*.py"):
            if f.is_symlink():
                continue
            for test in skip_list:
                ignore_content.append(f"{f} {test}")
        ignore_file = ignore_dir / f"ignore-{version}.txt"
        ignore_file.write_text("\n".join(sorted(set(ignore_content))).lstrip("\n"))
