trigger:
  batch: true
  branches:
    include:
      - main
      - stable-*

pr:
  autoCancel: true
  branches:
    include:
      - main
      - stable-*

schedules:
  - cron: 0 9 * * *
    displayName: Nightly
    always: true
    branches:
      include:
        - main
        - stable-*

variables:
  - name: checkoutPath
    value: ansible_collections/community/aws
  - name: coverageBranches
    value: main
  - name: pipelinesCoverage
    value: coverage
  - name: entryPoint
    value: tests/utils/shippable/shippable.sh
  - name: fetchDepth
    value: 0

resources:
  containers:
    - container: default
      image: quay.io/ansible/azure-pipelines-test-container:1.7.1

pool: Standard

stages:
### Sanity
  - stage: Sanity_devel
    displayName: Sanity devel
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: Test 1 {0}
          testFormat: devel/sanity/1/{0}
          targets:
            - test: ''
  - stage: Sanity_2_10
    displayName: Sanity 2.10
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: Test 1 {0}
          testFormat: 2.10/sanity/1/{0}
          targets:
            - test: ''
  - stage: Sanity_2_9
    displayName: Sanity 2.9
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: Test 1 {0}
          testFormat: 2.9/sanity/1/{0}
          targets:
            - test: ''
### Units
  - stage: Units_devel
    displayName: Units devel
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: Python {0}
          testFormat: devel/units/{0}/1
          targets:
            - test: 2.7
            - test: 3.6
            - test: 3.7
            - test: 3.8
            - test: 3.9
  - stage: Units_2_10
    displayName: Units 2.10
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: Python {0}
          testFormat: 2.10/units/{0}/1
          targets:
            - test: 2.7
            - test: 3.6
            - test: 3.7
            - test: 3.8
            - test: 3.9
  - stage: Units_2_9
    displayName: Units 2.9
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: Python {0}
          testFormat: 2.9/units/{0}/1
          targets:
            - test: 2.7
            - test: 3.6
            - test: 3.7
            - test: 3.8
### AWS Integration Tests
  - stage: AWS_devel
    displayName: AWS devel
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: Python {0}
          testFormat: devel/aws/{0}
          targets:
            - test: 2.7
            - test: 3.7
          groups:
            - 1
            - 2
            - 3
            - 4
  - stage: AWS_2_10
    displayName: AWS 2.10
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: Python {0}
          testFormat: 2.10/aws/{0}
          targets:
            - test: 2.7
            - test: 3.7
          groups:
            - 1
            - 2
            - 3
            - 4
  - stage: AWS_2_9
    displayName: AWS 2.9
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: Python {0}
          testFormat: 2.9/aws/{0}
          targets:
            - test: 2.7
            - test: 3.7
          groups:
            - 1
            - 2
            - 3
            - 4

### Finally
  - stage: Summary
    condition: succeededOrFailed()
    dependsOn:
      - Sanity_devel
      - Sanity_2_10
      - Sanity_2_9
      - Units_devel
      - Units_2_9
      - Units_2_10
      - AWS_devel
      - AWS_2_10
      - AWS_2_9
    jobs:
      - template: templates/coverage.yml
