---
name: integration

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - main
      - stable-*
jobs:
  splitter:
    name: ansible test splitter
    permissions:
      pull-requests: read
    env:
      source_dir: "./community_aws"
    outputs:
      jobs: ${{ steps.compute.outputs.jobs }}
      targets: ${{ steps.compute.outputs.targets }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source collection
        uses: actions/checkout@v6
        with:
          path: "${{ env.source_dir }}"
          fetch-depth: 0

      - name: list changes for pull request
        id: compute
        uses: ansible/cloud-content-ci-automation/.github/actions/ansible_test_splitter@main
        with:
          collections_to_test: "${{ env.source_dir}}"
          total_jobs: 24
          base_ref: ${{ github.event.pull_request.base.ref }}

  run-tests:
    needs: splitter
    permissions:
      pull-requests: read
    env:
      source_dir: "./community_aws"
      all_targets: "${{ needs.splitter.outputs.targets }}"
      ansible_version: milestone
      python_version: 3.12
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job-id: ${{ fromJson(needs.splitter.outputs.jobs) }}
    name: "${{ matrix.job-id }}"
    steps:
      - name: Checkout the source collection
        uses: actions/checkout@v6
        with:
          path: "${{ env.source_dir }}"

      - name: Read job targets
        id: read-targets
        uses: ansible/cloud-content-ci-automation/.github/actions/ansible_read_targets@main
        with:
          job_id: "${{ matrix.job-id }}"
          all_targets: "${{ env.all_targets }}"

      - name: Build and install the source collection
        id: install-collection
        uses: ansible-network/github_actions/.github/actions/build_install_collection@main
        with:
          install_python_dependencies: false
          source_path: ${{ env.source_dir }}
      
      - name: Set up Python ${{ env.python_version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.python_version }}

      - name: Install collection's dependencies
        run: ansible-galaxy collection install -r tests/integration/requirements.yml
        working-directory: ${{ env.source_dir }}

      # Generate AWS temporary credentials used to run tests
      - uses: ansible/ansible-test-auth@v1

      - name: Run integration tests
        uses: ansible-network/github_actions/.github/actions/ansible_test_integration@main
        with:
          collection_path: ${{ steps.install-collection.outputs.collection_path }}
          python_version: ${{ env.python_version }}
          ansible_version: ${{ env.ansible_version }}
          ansible_test_targets: ${{ steps.read-targets.outputs.job_targets }}
          ansible_test_requirement_files: "tests/integration/requirements.txt"