---
name: unit tests

on: [workflow_call]  # allow this workflow to be called from other workflows

jobs:
  unit-source:
    uses: ansible-network/github_actions/.github/workflows/unit_source.yml@main
    with:
      collection_pre_install: '-r source/tests/unit/requirements.yml'
